ALTER TABLE doc_sources
    ADD COLUMN IF NOT EXISTS image_root TEXT NOT NULL DEFAULT '';

ALTER TABLE doc_chunks
    ADD COLUMN IF NOT EXISTS rel_path TEXT NOT NULL DEFAULT '';

ALTER TABLE doc_figures
    ADD COLUMN IF NOT EXISTS image_path TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ocr_text TEXT NOT NULL DEFAULT '';
